### ISSUE TITLE
Label URL returns empty string

### ISSUE THREAD

**Issue by claw68** [goshippo/shippo-php-client#20]
```
$transaction = Shippo_Transaction::create( Array(
'rate' => $rate->object_id,
'label_file_type' => 'PDF'
));
```

Returns a blank `label_url`. I wanted to retrieve the URL of the Label same with what I have in my shippo dashboard.

**Comment by sbeidas** [comment]
Thank you for writing in!

Do you have the `object_id` of the particular Transaction object?

I suspect that the `label_url` was empty because the `object_status` for the Transaction was `ERROR` or `QUEUED`

**Comment by claw68** [comment]
@sbeidas  Transaction object_id: 7bf91ee405d444339ceb0c57cde7fc2a

You are correct, object_status is QUEUED. However, in my shippo dashboard -> shipments there's a download link to a sample pdf. Is there a way to retrieve the sample label pdf?

**Comment by sbeidas** [comment]
@claw68 

From the code snippet you shared above, the async attribute is not set, this defaults the Transaction's creation to be asynchronous. This means that the $transaction's object_status will be`QUEUED` and there will be no label_url since the creation of the label is still in progress. If you refresh the object after sometime you'll see that the Transaction `object_status` will be no longer be `QUEUED`

You can create the Transaction synchronously by setting the `async` attribute to false (See below)

``
$transaction = Shippo_Transaction::create( Array(
'rate' => $rate->object_id,
'label_file_type' => 'PDF',
'async' => false
));
``

I hope this helps, please do let me know if you have any additional questions
