### ISSUE TITLE
Upgrading to namespaces?

### ISSUE THREAD

**Issue by casperbakker** [goshippo/shippo-php-client#39]
This package looks a bit dated to integrate into our app. Are there any plans to upgrade to >= PHP 5.3 and add name spacing?

**Comment by mootrichard** [comment]
Our wrapper currently requires PHP >= 5.3, but as for the name-spacing, I am actually highlighting this for our dev team to look into implementing.  

It appears that we had bumped up the required version of PHP up to 5.6 so that our tests would pass, but we're taking a closer look as to whether the tests are the limiting factor for supporting 5.3 or if the wrapper itself requires the upgrade.

**Comment by casperbakker** [comment]
Great. The PHP versions between 5.2 and 5.6 do not have a lot of breaking stuff, mostly new features and differences in regular expressions. So upgrading that should not be the biggest issue.

If I can help with anything, please ping me.
